export interface LoginData {
  email: string;
  password: string;
}
export interface LoginResponse {
  ok: boolean;
  msg: string;
  data: Data;
}

export interface Data {
  token: string;
}

// Generated by https://quicktype.io

export interface GetRenewToken {
  ok: boolean;
  msg: string;
  data: Data;
}

export interface Data {
  token: string;
}

// Generated by https://quicktype.io

export interface UserLogged {
  ok: boolean;
  msg: string;
  data: Data;
}

export interface Data {
  user: User;
}

export interface User {
  id?: number;
  role_id?: number;
  email?: string;
  full_name?: string;
  identification?: string;
  phone?: string;
  photo?: string;
  photo_id_front?: string;
  photo_id_back?: string;
  photo_licence_front?: string;
  photo_licence_back?: string;
  is_active?: boolean;
  is_available?:boolean;
  expo_token?:string;
  created_at?: string;
  lat?:number,
  lng?:number,
  // uid?:string,
}


export interface RegisterUserResponse {
  ok: boolean;
  msg: string;
  data: Data;
}

export interface Data {
  id: number;
}

export interface ResponseUpdateUser {
  ok: boolean;
  msg: string;
  data: Data;
}

export interface Data {
  id: number;
  role_id: number;
  email: string;
  full_name: string;
  identification: string;
  phone: string;
  photo: string;
  photo_id_front: string;
  photo_id_back: string;
  photo_licence_front: string;
  photo_licence_back: string;
  is_active: boolean;
  created_at: string;
  lat?:number,
  lng?:number
}