// Generated by https://quicktype.io

export interface ResponseChat {
    ok:   boolean;
    msg:  string;
    data: Datum[];
}

export interface Datum {
    sender_id:   number;
    receiver_id: number;
    message:     string;
    created_at:  string;
}
