
export interface DeleteUserResponse {
    ok:   boolean;
    msg:  string;
    data: Data;
}

export interface Data {
}

// Generated by https://quicktype.io

export interface GetDataAdmins {
    ok:   boolean;
    msg:  string;
    data: DataAdmin[];
}

export interface DataAdmin {
    id:        number;
    full_name: string;
    photo:     null | string;
}
